### ISSUE TITLE
Roadmap: Integration into different Sigstore implementations

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/sigstore-conformance#61]
This is a roadmap issue tracking our integration of the conformance suite into different Sigstore implementations:

- [ ] `sigstore-python`: https://github.com/sigstore/sigstore-python/issues/297
    - [ ] https://github.com/sigstore/sigstore-python/pull/298
- [ ] `sigstore-java`: https://github.com/sigstore/sigstore-java/issues/236
    - [ ] https://github.com/sigstore/sigstore-java/pull/245
- [ ] `sigstore-go`
